AppBundle\Entity\Playlist:
    type: entity
    table: mp_playlist
    repositoryClass: AppBundle\Repository\PlaylistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: false
    lifecycleCallbacks: {  }
